### ISSUE TITLE
Add covariance in FormItem 

### ISSUE THREAD

**Issue by vladtaraban** [fedandburk/buform#33]
Currently we can't use inherited FormItem and FormCell in one time, so we need to fix it to make out Forms more expandable.

**Comment by vladtaraban** [comment]
Hi @prin53 , Updated status on this. I have faced some problems with using covariance here. It isn’t possible to properly check type of FormItem we use in Cell. I have tried to add generic interfaces, but it isn't what we need, as covariance works only for output parameters and not for input. But I found simplier solution, which looks good for me. We can just make our FormCells generic and when you want to reuse it, you can pass your FormItem type there.

Example:

- Custom FormItem

`public class CustomButtonFormItem : ButtonFormItem`

- Custom FormCell

`public class CustomButtonFormCell : ButtonFormCell<CustomButtonFormItem>`

- Changes to ButtonFormCell

`public class ButtonFormCell<TButtonFormItem> : FormCell<TButtonFormItem> where TButtonFormItem : ButtonFormItem`

This solution is clean and simple, but I faced one small problem with TableView. As we use DequeueReusableCell which takes identifier it doesn't support Generic ViewCells. So, for default implementation we can just add 
`public class ButtonFormCell : ButtonFormCell<ButtonFormItem>`. 
Also it has minimal impact on our code as I don't change any logic for registration or resolving ViewCells, so I think we shouldn't get any bugs.
 What are your thoughts on this?

**Comment by prin53** [comment]
@vladtaraban I like the last solution as we always should have some concrete type to work with in sources/adapters. Let's go for it 👍

**Comment by vladtaraban** [comment]
@prin53 , I will rewrite current FormCells and create PR today
